/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2019-01-15 12:59:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class rejister_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>个人注册</title>\r\n");
      out.write("<style>\r\n");
      out.write(".all{\r\n");
      out.write("\tbackground:white;\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\theight:100%;\r\n");
      out.write("}\r\n");
      out.write(".login_input {\r\n");
      out.write("\tpadding: 5px;\r\n");
      out.write("\theight: 20px;\r\n");
      out.write("\tline-height: 20px;\r\n");
      out.write("\tcolor: gray;\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("\tmargin-bottom: 10px;\r\n");
      out.write("\tborder: 1px solid #ccc;\r\n");
      out.write("}\r\n");
      out.write(".login_name h3 {\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\tborder-bottom: 1px dotted #02356f;\r\n");
      out.write("}\r\n");
      out.write(".login_button{background:#008ffd;border-radius:5px;width:120px;height:35px;line-heihgt:35px;display:block; margin-top:10px; color:white; border:none; font-family:microsoft yahei;cursor:pointer;}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar xmlHttp;\r\n");
      out.write("\tfunction checkIt()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar username = document.getElementById(\"username\").value;\r\n");
      out.write("\t\txmlHttp = new XMLHttpRequest();\r\n");
      out.write("\t\tvar url=\"UserCheckServlet?username=\"+username;\r\n");
      out.write("\t\txmlHttp.open(\"GET\",url,true);\r\n");
      out.write("\t\txmlHttp.send();\r\n");
      out.write("\t\txmlHttp.onreadystatechange=function()\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tif (xmlHttp.readyState==4 && xmlHttp.status==200)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t//给div设置内容\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"errorAccount\").innerHTML = xmlHttp.responseText;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction validate() \r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(document.getElementById(\"username\").value == \"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"用户登录名不能为空！\");\r\n");
      out.write("\t\t\t//document.getElementById(\"username\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(document.getElementById(\"password\").value == \"\")\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\talert(\"登录密码不能为空！\");\r\n");
      out.write("\t\t\tdocument.getElementById(\"password\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t var password = document.getElementById(\"password\").value;\r\n");
      out.write("\t\t\t\t              var userpassword = document.getElementById(\"userpassword\").value;\r\n");
      out.write("\t\t\t\t              if(password == userpassword) {\r\n");
      out.write("\t\t\t\t                  return true;\r\n");
      out.write("\t\t\t\t              }\r\n");
      out.write("\t\t\t\t              else {\r\n");
      out.write("\t\t\t\t\t\t\t\t\talert(\"两次密码不一致！\");\r\n");
      out.write("\t\t\t\t                  return false;\r\n");
      out.write("\t\t\t\t              }\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"all\">\r\n");
      out.write("\t<div class=\"top\" style=\"width:100%; height:150px;\">\r\n");
      out.write("\t\t<div class=\"left\" style=\"float:left ; width:50%; height:100%;\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"right\" align=\"center\" style=\"float:left ; width:50%; height:100%;\">\r\n");
      out.write("\t\t\t已有账户？<a href=\"login.jsp\">请登录</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"main\" style=\"width:100%;height:600px\">\r\n");
      out.write("\t\t<h3 align=\"center\">用户注册</h3>\r\n");
      out.write("\t\t\t<form action=\"RegisterServlet\" method=\"post\">\r\n");
      out.write("\t\t\t\t<div align=\"center\" id=\"errorAccount\" >\r\n");
      out.write("\t\t\t\t\t用&nbsp;&nbsp;户&nbsp;&nbsp;名：<input name=\"username\" id=\"username\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" type=\"text\" onblur=\"checkIt()\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"login_input\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t\t\t密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码：<input name=\"password\" id=\"password\"\r\n");
      out.write("\t\t\t\t\t\ttype=\"password\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${password}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"login_input\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t\t\t确认密码：<input name=\"userpassword\" id=\"userpassword\"\r\n");
      out.write("\t\t\t\t\t\ttype=\"password\" class=\"login_input\" />\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" class=\"login_button\" value=\"注册成功\" onclick=\"return validate() \">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div  class=\"foot\" style=\"width:100%;height:30px\" align=\"center\">\r\n");
      out.write("\t   \t\t关于我们|联系我们|广告服务|人才招聘|友情链接\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
