package com.model;

/**
 * TLaoshi generated by MyEclipse Persistence Tools
 */

public class TLaoshi implements java.io.Serializable
{

	private Integer id;
	private String bianhao;
	private String xingming;
	private String xingbie;

	private String nianling;
	private String loginpw;
	private String del;
	
	
	public String getBianhao()
	{
		return bianhao;
	}
	public void setBianhao(String bianhao)
	{
		this.bianhao = bianhao;
	}
	public String getDel()
	{
		return del;
	}
	public void setDel(String del)
	{
		this.del = del;
	}
	public Integer getId()
	{
		return id;
	}
	public void setId(Integer id)
	{
		this.id = id;
	}
	public String getLoginpw()
	{
		return loginpw;
	}
	public void setLoginpw(String loginpw)
	{
		this.loginpw = loginpw;
	}
	public String getNianling()
	{
		return nianling;
	}
	public void setNianling(String nianling)
	{
		this.nianling = nianling;
	}
	public String getXingbie()
	{
		return xingbie;
	}
	public void setXingbie(String xingbie)
	{
		this.xingbie = xingbie;
	}
	public String getXingming()
	{
		return xingming;
	}
	public void setXingming(String xingming)
	{
		this.xingming = xingming;
	}

}