/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2019-03-28 03:08:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.qst.bean.BuytodayBean;
import java.util.List;
import com.qst.service.BuytodayService;
import com.qst.service.BuytodayServiceimp;
import com.qst.bean.BuytodayBean;
import com.qst.service.TmbuyService;
import com.qst.service.TmbuyServiceimp;
import com.qst.bean.TmbuyBean;

public final class buytoday_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1553064562566L));
    _jspx_dependants.put("jar:file:/E:/2015级内师大毕设git材料/NetWork_Graduation2015_Real/20151104697_zhongyangyang/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/20151104697_zhongyangyang_GraduationDesign/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.qst.service.TmbuyServiceimp");
    _jspx_imports_classes.add("com.qst.bean.TmbuyBean");
    _jspx_imports_classes.add("com.qst.service.BuytodayService");
    _jspx_imports_classes.add("com.qst.service.BuytodayServiceimp");
    _jspx_imports_classes.add("com.qst.service.TmbuyService");
    _jspx_imports_classes.add("com.qst.bean.BuytodayBean");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <title>Document</title>\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"../res/static/css/main.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"../res/layui/css/layui.css\">\r\n");
      out.write("  <script type=\"text/javascript\" src=\"../res/layui/layui.js\"></script>\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge,chrome=1\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"site-nav-bg\">\r\n");
      out.write("    <div class=\"site-nav w1200\">\r\n");
      out.write("      <p class=\"sn-back-home\">\r\n");
      out.write("        <i class=\"layui-icon layui-icon-home\"></i>\r\n");
      out.write("        <a href=\"#\">首页</a>\r\n");
      out.write("      </p>\r\n");
      out.write("      <div class=\"sn-quick-menu\">\r\n");
      out.write("        <div class=\"login\"><a href=\"login.html\">登录</a></div>\r\n");
      out.write("        <div class=\"sp-cart\"><a href=\"html/shopcart.html\">购物车</a></div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <div class=\"header\">\r\n");
      out.write("    <div class=\"headerLayout w1200\">\r\n");
      out.write("      <div class=\"headerCon\">\r\n");
      out.write("        <div class=\"mallSearch\">\r\n");
      out.write("          <form action=\"\" class=\"layui-form\" novalidate>\r\n");
      out.write("            <input type=\"text\" name=\"title\" required  lay-verify=\"required\" autocomplete=\"off\" class=\"layui-input\" placeholder=\"请输入需要的商品\">\r\n");
      out.write("            <button class=\"layui-btn\" lay-submit lay-filter=\"formDemo\">\r\n");
      out.write("                <i class=\"layui-icon layui-icon-search\"></i>\r\n");
      out.write("            </button>\r\n");
      out.write("            <input type=\"hidden\" name=\"\" value=\"\">\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <div class=\"content content-nav-base buytoday-content\">\r\n");
      out.write("    <div id=\"list-cont\">\r\n");
      out.write("      <div class=\"main-nav\">\r\n");
      out.write("        <div class=\"inner-cont0\">\r\n");
      out.write("          <div class=\"inner-cont1 w1200\">\r\n");
      out.write("            <div class=\"inner-cont2\">\r\n");
      out.write("              <a href=\"commodity.jsp\">所有商品</a>\r\n");
      out.write("              <a href=\"buytoday.html\" class=\"active\">今日团购</a>\r\n");
      out.write("              <a href=\"information.html\">手机资讯</a>\r\n");
      out.write("              <a href=\"about.html\">关于我们</a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"banner-box\">\r\n");
      out.write("        <div class=\"banner\"></div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"product-list-box\">\r\n");
      out.write("        <div class=\"product-list w1200\">  \r\n");
      out.write("          <div class=\"tab-title\">\r\n");
      out.write("            <a href=\"javascript:;\" class=\"active tuang\" data-content=\"tuangou\">今日团购</a>\r\n");
      out.write("            <a href=\"javascript:;\" data-content=\"yukao\">明日预告</a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"list-cont\" cont = 'tuangou'>\r\n");
      out.write("           ");

             		session.removeAttribute("list");
  					BuytodayService buyService = new BuytodayServiceimp();
                    List<BuytodayBean> list = buyService.getAllBuytoday();
                    session.setAttribute("list", list);
                     for(BuytodayBean buy:list){ 
                 
      out.write("\r\n");
      out.write("            <div class=\"item-box layui-clear\">\r\n");
      out.write("              <div class=\"item\">\r\n");
      out.write("                <img src=\"../res/static/img/tuan_img1.jpg\" alt=\"\">\r\n");
      out.write("                <div class=\"text-box\">\r\n");
      out.write("                  <p class=\"title\">");
      out.print(buy.getTyname());
      out.write("</p>\r\n");
      out.write("                  <p class=\"plic\">\r\n");
      out.write("                    <span class=\"ciur-pic\">");
      out.print(buy.getPresent());
      out.write("</span>\r\n");
      out.write("                    <span class=\"Ori-pic\">");
      out.print(buy.getOriginal());
      out.write("</span>\r\n");
      out.write("                    <span class=\"discount\">");
      out.print(buy.getDscount());
      out.write("</span>\r\n");
      out.write("                  </p>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            ");
} 
      out.write("\r\n");
      out.write("            <div id=\"demo0\" style=\"text-align: center;\"></div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>  \r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"footer-wrap\">\r\n");
      out.write("        <div class=\"footer w1200\">\r\n");
      out.write("          <div class=\"title\">\r\n");
      out.write("            <h3>团购销量榜</h3>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"list-box layui-clear\" id=\"footerList\">\r\n");
      out.write("           ");

             		session.removeAttribute("list");
  					TmbuyService tmService = new TmbuyServiceimp();
                    List<TmbuyBean> list = tmService.getAllTmbuy();
                    session.setAttribute("list", list);
                     for(TmbuyBean tm:list){ 
                 
      out.write("\r\n");
      out.write("            <div class=\"item\">\r\n");
      out.write("              <img src=\"../res/static/img/tuan_img5.jpg\" alt=\"\">\r\n");
      out.write("              <div class=\"text\">\r\n");
      out.write("                <div class=\"right-title-number\">");
      out.print(tm.getTmnum());
      out.write("</div>\r\n");
      out.write("                <div class=\"commod\">\r\n");
      out.write("                  <p>");
      out.print(tm.getTmname());
      out.write("</p>\r\n");
      out.write("                  <span>");
      out.print(tm.getTmprice());
      out.write("</span>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("             ");
} 
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("  layui.config({\r\n");
      out.write("    base: '../res/static/js/util/' //你存放新模块的目录，注意，不是layui的模块目录\r\n");
      out.write("  }).use(['mm','laypage','jquery'],function(){\r\n");
      out.write("      var laypage = layui.laypage,$ = layui.$;\r\n");
      out.write("     mm = layui.mm;\r\n");
      out.write("      laypage.render({\r\n");
      out.write("        elem: 'demo0'\r\n");
      out.write("        ,count: 100 //数据总数\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      $('body').on('click','*[data-content]',function(){\r\n");
      out.write("        $(this).addClass('active').siblings().removeClass('active')\r\n");
      out.write("        var dataConte = $(this).attr('data-content');\r\n");
      out.write("        $('*[cont]').each(function(i,item){\r\n");
      out.write("          var itemCont = $(item).attr('cont');\r\n");
      out.write("          console.log(item)\r\n");
      out.write("          if(dataConte === itemCont){\r\n");
      out.write("            $(item).removeClass('layui-hide');\r\n");
      out.write("          }else{\r\n");
      out.write("            $(item).addClass('layui-hide');\r\n");
      out.write("          }\r\n");
      out.write("        })\r\n");
      out.write("      })\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
