/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.24
 * Generated at: 2019-03-23 05:37:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.html;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.qst.bean.RecommendBean;
import java.util.List;
import com.qst.service.RecommendService;
import com.qst.service.RecommendServiceimp;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1553064562566L));
    _jspx_dependants.put("jar:file:/E:/2015级内师大毕设git材料/NetWork_Graduation2015_Real/20151104697_zhongyangyang/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/20151104697_zhongyangyang_GraduationDesign/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.qst.service.RecommendService");
    _jspx_imports_classes.add("com.qst.bean.RecommendBean");
    _jspx_imports_classes.add("com.qst.service.RecommendServiceimp");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <title>Document</title>\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"../20151104697_zhongyangyang_GraduationDesign/res/static/css/main.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"../20151104697_zhongyangyang_GraduationDesign/res/layui/css/layui.css\">\r\n");
      out.write("  <script type=\"text/javascript\" src=\"../20151104697_zhongyangyang_GraduationDesign/res/layui/layui.js\"></script>\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge,chrome=1\">\r\n");
      out.write("</head>\r\n");
      out.write("<body id=\"list-cont\">\r\n");
      out.write("  <div class=\"site-nav-bg\">\r\n");
      out.write("    <div class=\"site-nav w1200\">\r\n");
      out.write("      <p class=\"sn-back-home\">\r\n");
      out.write("        <i class=\"layui-icon layui-icon-home\"></i>\r\n");
      out.write("        <a href=\"#\">首页</a>\r\n");
      out.write("      </p>\r\n");
      out.write("      <div class=\"sn-quick-menu\">\r\n");
      out.write("        <div class=\"login\"><a href=\"login.jsp\">登录</a></div>\r\n");
      out.write("        <div class=\"sp-cart\"><a href=\"html/shopcart.html\">购物车</a></div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <div class=\"header\">\r\n");
      out.write("    <div class=\"headerLayout w1200\">\r\n");
      out.write("      <div class=\"headerCon\">\r\n");
      out.write("        <h1 class=\"mallLogo\">\r\n");
      out.write("          <a href=\"#\" title=\"手机商城\">\r\n");
      out.write("\r\n");
      out.write("          </a>\r\n");
      out.write("        </h1>\r\n");
      out.write("        <div class=\"mallSearch\">\r\n");
      out.write("          <form action=\"\" class=\"layui-form\" novalidate>\r\n");
      out.write("            <input type=\"text\" name=\"title\" required  lay-verify=\"required\" autocomplete=\"off\" class=\"layui-input\" placeholder=\"请输入需要的商品\">\r\n");
      out.write("            <button class=\"layui-btn\" lay-submit lay-filter=\"formDemo\">\r\n");
      out.write("                <i class=\"layui-icon layui-icon-search\"></i>\r\n");
      out.write("            </button>\r\n");
      out.write("            <input type=\"hidden\" name=\"\" value=\"\">\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <div class=\"content\">\r\n");
      out.write("    <div class=\"main-nav\">\r\n");
      out.write("      <div class=\"inner-cont0\">\r\n");
      out.write("        <div class=\"inner-cont1 w1200\">\r\n");
      out.write("          <div class=\"inner-cont2\">\r\n");
      out.write("            <a href=\"html/commodity.jsp\" class=\"active\">所有商品</a>\r\n");
      out.write("            <a href=\"html/buytoday.html\">今日团购</a>\r\n");
      out.write("            <a href=\"html/information.html\">手机资讯</a>\r\n");
      out.write("            <a href=\"html/about.html\">关于我们</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"category-con\">\r\n");
      out.write("      <div class=\"category-inner-con w1200\">\r\n");
      out.write("        <div class=\"category-type\">\r\n");
      out.write("          <h3>全部分类</h3>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"category-tab-content\">\r\n");
      out.write("          <div class=\"nav-con\">\r\n");
      out.write("            <ul class=\"normal-nav layui-clear\">\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <div class=\"title\">华为</div>\r\n");
      out.write("                <p><a href=\"#\">新款</a><a href=\"#\">爆款</a><a href=\"#\">性价比</a></p>\r\n");
      out.write("                <i class=\"layui-icon layui-icon-right\"></i>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <div class=\"title\">小米</div>\r\n");
      out.write("                <p><a href=\"#\">手机</a><a href=\"#\">平板</a></p>\r\n");
      out.write("                <i class=\"layui-icon layui-icon-right\"></i>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <div class=\"title\">iPhone</div>\r\n");
      out.write("                <p><a href=\"#\">手机</a><a href=\"#\">平板</a></p>\r\n");
      out.write("                <i class=\"layui-icon layui-icon-right\"></i>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <div class=\"title\">vivo</div>\r\n");
      out.write("                <p><a href=\"#\">新款</a><a href=\"#\">爆款</a><a href=\"#\">性价比</a></p>\r\n");
      out.write("                <i class=\"layui-icon layui-icon-right\"></i>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <div class=\"title\">OPPO</div>\r\n");
      out.write("                <p><a href=\"#\">新款</a><a href=\"#\">爆款</a></p>\r\n");
      out.write("                <i class=\"layui-icon layui-icon-right\"></i>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <div class=\"title\">三星</div>\r\n");
      out.write("                <p><a href=\"#\">新款</a><a href=\"#\">爆款</a><a href=\"#\">性价比</a></p>\r\n");
      out.write("                <i class=\"layui-icon layui-icon-right\"></i>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item\">\r\n");
      out.write("                <div class=\"title\">摩托罗拉</div>\r\n");
      out.write("                <p><a href=\"#\">新款</a><a href=\"#\">爆款</a><a href=\"#\">性价比</a></p>\r\n");
      out.write("                <i class=\"layui-icon layui-icon-right\"></i>\r\n");
      out.write("              </li>\r\n");
      out.write("              <li class=\"nav-item nobor\">\r\n");
      out.write("                <div class=\"title\">金立</div>\r\n");
      out.write("                <p><a href=\"#\">新款</a><a href=\"#\">爆款</a><a href=\"#\">性价比</a></p>\r\n");
      out.write("                <i class=\"layui-icon layui-icon-right\"></i>\r\n");
      out.write("              </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"category-banner\">\r\n");
      out.write("        <div class=\"w1200\">\r\n");
      out.write("          <img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/hw5g.jpg\" style=\"width:1200px;height:400px\" >\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"floors\">\r\n");
      out.write("      <div class=\"sk\">\r\n");
      out.write("        <div class=\"sk_inner w1200\">\r\n");
      out.write("          <div class=\"sk_hd\">\r\n");
      out.write("            <a href=\"javascript:;\">\r\n");
      out.write("              <img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/s_img1.jpg\">\r\n");
      out.write("            </a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"sk_bd\">\r\n");
      out.write("            <div class=\"layui-carousel\" id=\"test1\">\r\n");
      out.write("              <div carousel-item>\r\n");
      out.write("                <div class=\"item-box\">\r\n");
      out.write("                  <div class=\"item\">\r\n");
      out.write("                    <a href=\"javascript:;\"><img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/s_img2.jpg\"></a>\r\n");
      out.write("                    <div class=\"title\">宝宝五彩袜棉质舒服</div>\r\n");
      out.write("                    <div class=\"price\">\r\n");
      out.write("                      <span>￥49.00</span>\r\n");
      out.write("                      <del>￥99.00</del>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"item\">\r\n");
      out.write("                    <a href=\"javascript:;\"><img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/s_img3.jpg\"></a>\r\n");
      out.write("                    <div class=\"title\">宝宝五彩袜棉质舒服</div>\r\n");
      out.write("                    <div class=\"price\">\r\n");
      out.write("                      <span>￥49.00</span>\r\n");
      out.write("                      <del>￥99.00</del>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"item\">\r\n");
      out.write("                    <a href=\"javascript:;\"><img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/s_img4.jpg\"></a>\r\n");
      out.write("                    <div class=\"title\">宝宝五彩袜棉质舒服</div>\r\n");
      out.write("                    <div class=\"price\">\r\n");
      out.write("                      <span>￥49.00</span>\r\n");
      out.write("                      <del>￥99.00</del>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"item\">\r\n");
      out.write("                    <a href=\"javascript:;\"><img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/s_img5.jpg\"></a>\r\n");
      out.write("                    <div class=\"title\">宝宝五彩袜棉质舒服</div>\r\n");
      out.write("                    <div class=\"price\">\r\n");
      out.write("                      <span>￥49.00</span>\r\n");
      out.write("                      <del>￥99.00</del>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"item-box\">\r\n");
      out.write("                  <div class=\"item\">\r\n");
      out.write("                    <a href=\"javascript:;\"><img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/s_img2.jpg\"></a>\r\n");
      out.write("                    <div class=\"title\">宝宝五彩袜棉质舒服</div>\r\n");
      out.write("                    <div class=\"price\">\r\n");
      out.write("                      <span>￥49.00</span>\r\n");
      out.write("                      <del>￥99.00</del>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"item\">\r\n");
      out.write("                    <a href=\"javascript:;\"><img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/s_img3.jpg\"></a>\r\n");
      out.write("                    <div class=\"title\">宝宝五彩袜棉质舒服</div>\r\n");
      out.write("                    <div class=\"price\">\r\n");
      out.write("                      <span>￥49.00</span>\r\n");
      out.write("                      <del>￥99.00</del>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"item\">\r\n");
      out.write("                    <a href=\"javascript:;\"><img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/s_img4.jpg\"></a>\r\n");
      out.write("                    <div class=\"title\">宝宝五彩袜棉质舒服</div>\r\n");
      out.write("                    <div class=\"price\">\r\n");
      out.write("                      <span>￥49.00</span>\r\n");
      out.write("                      <del>￥99.00</del>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"item\">\r\n");
      out.write("                    <a href=\"javascript:;\"><img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/s_img5.jpg\"></a>\r\n");
      out.write("                    <div class=\"title\">宝宝五彩袜棉质舒服</div>\r\n");
      out.write("                    <div class=\"price\">\r\n");
      out.write("                      <span>￥49.00</span>\r\n");
      out.write("                      <del>￥99.00</del>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>    \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"hot-recommend-con\">\r\n");
      out.write("      <div class=\"tlinks\">Collect from <a href=\"http://www.cssmoban.com/\" >网页模板</a></div>\r\n");
      out.write("       <div class=\"hot-con1 w1200 layui-clear\">\r\n");
      out.write("          <div class=\"item\">\r\n");
      out.write("            <h4>热销推荐</h4>\r\n");
      out.write("            <div class=\"big-img\">\r\n");
      out.write("              <a href=\"javascript:;\"><img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/hw5g.jpg\"style=\"width:300px;height:200px\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"small-img\">\r\n");
      out.write("              <a href=\"javascript:;\"><img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/iPhonex.jpg\"style=\"width:340px;height:100px\" alt=\"\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"item\">\r\n");
      out.write("            <div class=\"top-img\">\r\n");
      out.write("              <a href=\"javascript:;\"><img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/vivox21.jpg\"style=\"width:350px;height:220px\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"bottom-img\">\r\n");
      out.write("              <a href=\"javascript:;\"><img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/xm8.jpg\"style=\"width:170px;height:220px\"></a>\r\n");
      out.write("              <a class=\"baby-cream\" href=\"javascript:;\"><img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/opr15.jpg\"style=\"width:170px;height:220px\"></a>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"item item1 margin0 padding0\">\r\n");
      out.write("            <a href=\"javascript:;\"><img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/sxs9.jpg\"style=\"width:380px;height:240px\"></a>\r\n");
      out.write("            <a href=\"javascript:;\"><img class=\"btm-img\" src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/jl.jpg\"style=\"width:380px;height:240px\"></a>\r\n");
      out.write("          </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"product-cont w1200\" id=\"product-cont\">\r\n");
      out.write("      <div class=\"product-item product-item1 layui-clear\">\r\n");
      out.write("        <div class=\"left-title\">\r\n");
      out.write("          <h4><i>1F</i></h4>\r\n");
      out.write("          <img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/icon_gou.png\">\r\n");
      out.write("          <h5>华为</h5>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"right-cont\">\r\n");
      out.write("          <a href=\"javascript:;\" class=\"top-img\"><img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/hwl.jpg\"style=\"width:1000px;height:200px\" alt=\"\"></a>\r\n");
      out.write("          <div class=\"img-box\">\r\n");
      out.write("            <a href=\"javascript:;\"><img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/hwm.jpg\"style=\"width:199px;height:196px\"></a>\r\n");
      out.write("            <a href=\"javascript:;\"><img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/hwm.jpg\"style=\"width:199px;height:196px\"></a>\r\n");
      out.write("            <a href=\"javascript:;\"><img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/hwm.jpg\"style=\"width:199px;height:196px\"></a>\r\n");
      out.write("            <a href=\"javascript:;\"><img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/hwm.jpg\"style=\"width:199px;height:196px\"></a>\r\n");
      out.write("            <a href=\"javascript:;\"><img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/hwm.jpg\"style=\"width:199px;height:196px\"></a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"product-item product-item2 layui-clear\">\r\n");
      out.write("        <div class=\"left-title\">\r\n");
      out.write("          <h4><i>2F</i></h4>\r\n");
      out.write("          <img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/icon_gou.png\">\r\n");
      out.write("          <h5>iPhone</h5>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"right-cont\">\r\n");
      out.write("          <a href=\"javascript:;\" class=\"top-img\"><img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/ipl.jpg\"style=\"width:1000px;height:200px\" alt=\"\"></a>\r\n");
      out.write("          <div class=\"img-box\">\r\n");
      out.write("            <a href=\"javascript:;\"><img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/ip6.jpg\"style=\"width:199px;height:196px\"></a>\r\n");
      out.write("            <a href=\"javascript:;\"><img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/ip6.jpg\"style=\"width:199px;height:196px\"></a>\r\n");
      out.write("            <a href=\"javascript:;\"><img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/ip6.jpg\"style=\"width:199px;height:196px\"></a>\r\n");
      out.write("            <a href=\"javascript:;\"><img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/ip6.jpg\"style=\"width:199px;height:196px\"></a>\r\n");
      out.write("            <a href=\"javascript:;\"><img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/ip6.jpg\"style=\"width:199px;height:196px\"></a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"product-item product-item3 layui-clear\">\r\n");
      out.write("        <div class=\"left-title\">\r\n");
      out.write("          <h4><i>3F</i></h4>\r\n");
      out.write("          <img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/icon_gou.png\">\r\n");
      out.write("          <h5>小米</h5>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"right-cont\">\r\n");
      out.write("          <a href=\"javascript:;\" class=\"top-img\"><img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/xml.jpg\"style=\"width:1000px;height:200px\" alt=\"\"></a>\r\n");
      out.write("          <div class=\"img-box\">\r\n");
      out.write("            <a href=\"javascript:;\"><img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/xm8.jpg\"style=\"width:199px;height:196px\"></a>\r\n");
      out.write("            <a href=\"javascript:;\"><img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/xm8.jpg\"style=\"width:199px;height:196px\"></a>\r\n");
      out.write("            <a href=\"javascript:;\"><img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/xm8.jpg\"style=\"width:199px;height:196px\"></a>\r\n");
      out.write("            <a href=\"javascript:;\"><img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/xm8.jpg\"style=\"width:199px;height:196px\"></a>\r\n");
      out.write("            <a href=\"javascript:;\"><img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/xm8.jpg\"style=\"width:199px;height:196px\"></a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"product-list-box\" id=\"product-list-box\">\r\n");
      out.write("      <div class=\"product-list-cont w1200\">\r\n");
      out.write("        <h4>更多推荐</h4>\r\n");
      out.write("        ");

             		session.removeAttribute("list");
  					RecommendService recService = new RecommendServiceimp();
                    List<RecommendBean> list = recService.getAllRecommend();
                    session.setAttribute("list", list);
                     for(RecommendBean rec:list){
                 
      out.write("\r\n");
      out.write("        <div class=\"product-item-box layui-clear\">\r\n");
      out.write("          <div class=\"list-item\">\r\n");
      out.write("            <a href=\"javascript:;\"><img src=\"../20151104697_zhongyangyang_GraduationDesign/res/static/img/more1.jpg\"></a>\r\n");
      out.write("            <p>");
      out.print(rec.getComname() );
      out.write("</p>\r\n");
      out.write("            <span>");
      out.print(rec.getPrice());
      out.write("</span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
} 
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"footer\">\r\n");
      out.write("    <div class=\"ng-promise-box\">\r\n");
      out.write("      <div class=\"ng-promise w1200\">\r\n");
      out.write("        <p class=\"text\">\r\n");
      out.write("          <a class=\"icon1\" href=\"javascript:;\">7天无理由退换货</a>\r\n");
      out.write("          <a class=\"icon2\" href=\"javascript:;\">满99元全场免邮</a>\r\n");
      out.write("          <a class=\"icon3\" style=\"margin-right: 0\" href=\"javascript:;\">100%品质保证</a>\r\n");
      out.write("        </p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"mod_help w1200\">                                     \r\n");
      out.write("      <p>\r\n");
      out.write("        <a href=\"javascript:;\">关于我们</a>\r\n");
      out.write("        <span>|</span>\r\n");
      out.write("        <a href=\"javascript:;\">帮助中心</a>\r\n");
      out.write("        <span>|</span>\r\n");
      out.write("        <a href=\"javascript:;\">售后服务</a>\r\n");
      out.write("        <span>|</span>\r\n");
      out.write("        <a href=\"javascript:;\">手机资讯</a>\r\n");
      out.write("        <span>|</span>\r\n");
      out.write("        <a href=\"javascript:;\">关于货源</a>\r\n");
      out.write("      </p>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("layui.config({\r\n");
      out.write("    base: '../res/static/js/util/' //你存放新模块的目录，注意，不是layui的模块目录\r\n");
      out.write("  }).use(['mm','carousel'],function(){\r\n");
      out.write("      var carousel = layui.carousel,\r\n");
      out.write("     mm = layui.mm;\r\n");
      out.write("     var option = {\r\n");
      out.write("        elem: '#test1'\r\n");
      out.write("        ,width: '100%' //设置容器宽度\r\n");
      out.write("        ,arrow: 'always'\r\n");
      out.write("        ,height:'298' \r\n");
      out.write("        ,indicator:'none'\r\n");
      out.write("      }\r\n");
      out.write("      carousel.render(option);\r\n");
      out.write("});\r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
